spring.application.name=gasworks-api

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/gasworks_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=password

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger UI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs