spring.application.name=gasworks-api

# 他からの上書きを絶対に許さない設定（H2データベースを強制指定）
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# SQLの初期化スクリプト（schema.sql / data.sql）を強制的に毎回実行する設定
spring.sql.init.mode=always

# ポート番号
server.port=8081