# Generated by Django 5.2 on 2026-06-02 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='顧客ID')),
                ('name', models.CharField(max_length=255, verbose_name='顧客名')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('contact', models.CharField(max_length=255, verbose_name='連絡先')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '顧客情報',
                'verbose_name_plural': '顧客情報一覧',
                'db_table': 'customers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('name', models.CharField(max_length=255, verbose_name='ユーザー名')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=255, verbose_name='パスワード')),
                ('role', models.CharField(max_length=50, verbose_name='役割')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ユーザー情報',
                'verbose_name_plural': 'ユーザー情報一覧',
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='メーター読数ID')),
                ('reading_date', models.DateField(verbose_name='読取日')),
                ('reading_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='読取値')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer', verbose_name='顧客ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='作業員ID')),
            ],
            options={
                'verbose_name': '検針データ',
                'verbose_name_plural': '検針データ一覧',
                'db_table': 'meter_readings',
                'managed': True,
            },
        ),
    ]
